In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
car = pd.read_csv(r'C:\projects_sree\dataset.zip')

In [2]:
car.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0            I10  2017   7495       Manual    11630   Petrol  145  60.1   
1           Polo  2017  10989       Manual     9200   Petrol  145  58.9   
2       2 Series  2019  27990    Semi-Auto     1614   Diesel  145  49.6   
3   Yeti Outdoor  2017  12495       Manual    30960   Diesel  150  62.8   
4         Fiesta  2017   7999       Manual    19353   Petrol  125  54.3   

   engineSize Manufacturer  
0         1.0       hyundi  
1         1.0   volkswagen  
2         2.0          BMW  
3         2.0        skoda  
4         1.2         ford

In [3]:
car.shape


(97712, 10)

In [4]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97712 entries, 0 to 97711
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         97712 non-null  object 
 1   year          97712 non-null  int64  
 2   price         97712 non-null  int64  
 3   transmission  97712 non-null  object 
 4   mileage       97712 non-null  int64  
 5   fuelType      97712 non-null  object 
 6   tax           97712 non-null  int64  
 7   mpg           97712 non-null  float64
 8   engineSize    97712 non-null  float64
 9   Manufacturer  97712 non-null  object 
dtypes: float64(2), int64(4), object(4)
memory usage: 7.5+ MB


In [5]:
car['year'].unique()

array([2017, 2019, 2018, 2016, 2020, 2015, 2014, 2013, 2008, 2011, 2010,
       2012, 2007, 2009, 2003, 1998, 2006, 2002, 2005, 2004, 2001, 2000,
       1997, 1999, 1996, 2024, 1970], dtype=int64)

In [6]:
car['price'].unique()

array([ 7495, 10989, 27990, ..., 23448,  4871, 18217], dtype=int64)

In [7]:
car['mileage'].unique()

array([11630,  9200,  1614, ..., 22635, 25570, 25372], dtype=int64)

In [8]:
car['fuelType'].unique()

array(['Petrol', 'Diesel', 'Hybrid', 'Other', 'Electric'], dtype=object)

In [9]:
car['model'].unique()

array([' I10', ' Polo', ' 2 Series', ' Yeti Outdoor', ' Fiesta', ' C-HR',
       ' Kuga', ' Tiguan', ' A Class', ' 1 Series', ' Up', ' Golf',
       ' Corsa', ' RAV4', ' GLA Class', ' Aygo', ' Q5', ' Karoq',
       ' Scala', ' Auris', ' Tucson', ' A4', ' Viva', ' Kodiaq',
       ' C Class', ' Mondeo', ' Citigo', ' Yaris', ' X4', ' Octavia',
       ' Astra', ' Focus', ' 3 Series', ' GLC Class', ' Q3', ' B-MAX',
       ' C-MAX', ' IX20', ' X5', ' T-Cross', ' Shuttle', ' Insignia',
       ' Zafira', ' A3', ' A5', ' SL CLASS', ' EcoSport', ' X1', ' Fabia',
       ' Golf SV', ' Verso', ' Yeti', ' Mokka X', ' Antara', ' E Class',
       ' 4 Series', ' Superb', ' 5 Series', ' 8 Series', ' B Class',
       ' Ka+', ' X2', ' GLE Class', ' A6', ' Mokka', ' Passat', ' Kamiq',
       ' Adam', ' Q7', ' Tiguan Allspace', ' X3', ' A1', ' Grandland X',
       ' Meriva', ' Tourneo Connect', ' Arteon', ' TT', ' GLS Class',
       ' Santa Fe', ' I30', ' S Class', ' Ioniq', ' Edge', ' S-MAX',
       ' SLK'

In [10]:
backup=car.copy()

In [11]:
car.describe()

year          price        mileage           tax           mpg  \
count  97712.000000   97712.000000   97712.000000  97712.000000  97712.000000   
mean    2017.066502   16773.487555   23219.475499    120.142408     55.205623   
std        2.118661    9868.552222   21060.882301     63.357250     16.181659   
min     1970.000000     450.000000       1.000000      0.000000      0.300000   
25%     2016.000000    9999.000000    7673.000000    125.000000     47.100000   
50%     2017.000000   14470.000000   17682.500000    145.000000     54.300000   
75%     2019.000000   20750.000000   32500.000000    145.000000     62.800000   
max     2024.000000  159999.000000  323000.000000    580.000000    470.800000   

         engineSize  
count  97712.000000  
mean       1.664913  
std        0.558574  
min        0.000000  
25%        1.200000  
50%        1.600000  
75%        2.000000  
max        6.600000

Model

In [12]:
x = car.drop(['price','tax'],axis=1)
y = car['price']

In [13]:
x.columns, y.name

(Index(['model', 'year', 'transmission', 'mileage', 'fuelType', 'mpg',
        'engineSize', 'Manufacturer'],
       dtype='object'),
 'price')

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [16]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97712 entries, 0 to 97711
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         97712 non-null  object 
 1   year          97712 non-null  int64  
 2   price         97712 non-null  int64  
 3   transmission  97712 non-null  object 
 4   mileage       97712 non-null  int64  
 5   fuelType      97712 non-null  object 
 6   tax           97712 non-null  int64  
 7   mpg           97712 non-null  float64
 8   engineSize    97712 non-null  float64
 9   Manufacturer  97712 non-null  object 
dtypes: float64(2), int64(4), object(4)
memory usage: 7.5+ MB


In [17]:
ohe = OneHotEncoder()
ohe.fit(x[['model','transmission','fuelType','Manufacturer']])

OneHotEncoder()

In [18]:
ohe.categories_

[array([' 1 Series', ' 2 Series', ' 3 Series', ' 4 Series', ' 5 Series',
        ' 6 Series', ' 7 Series', ' 8 Series', ' A Class', ' A1', ' A2',
        ' A3', ' A4', ' A5', ' A6', ' A7', ' A8', ' Accent', ' Adam',
        ' Agila', ' Amarok', ' Amica', ' Ampera', ' Antara', ' Arteon',
        ' Astra', ' Auris', ' Avensis', ' Aygo', ' B Class', ' B-MAX',
        ' Beetle', ' C Class', ' C-HR', ' C-MAX', ' CC', ' CL Class',
        ' CLA Class', ' CLC Class', ' CLK', ' CLS Class', ' Caddy',
        ' Caddy Life', ' Caddy Maxi', ' Caddy Maxi Life', ' California',
        ' Camry', ' Caravelle', ' Cascada', ' Citigo', ' Combo Life',
        ' Corolla', ' Corsa', ' Crossland X', ' E Class', ' EcoSport',
        ' Edge', ' Eos', ' Escort', ' Fabia', ' Fiesta', ' Focus', ' Fox',
        ' Fusion', ' G Class', ' GL Class', ' GLA Class', ' GLB Class',
        ' GLC Class', ' GLE Class', ' GLS Class', ' GT86', ' GTC',
        ' Galaxy', ' Getz', ' Golf', ' Golf SV', ' Grand C-MAX',
        ' 

In [19]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['model','transmission','fuelType','Manufacturer']),remainder='passthrough')

In [20]:
lr=LinearRegression()

In [21]:
pipe = make_pipeline(column_trans,lr)

In [22]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array([' 1 Series', ' 2 Series', ' 3 Series', ' 4 Series', ' 5 Series',
       ' 6 Series', ' 7 Series', ' 8 Series', ' A Class', ' A1', ' A2',
       ' A3', ' A4', ' A5', ' A6', ' A7', ' A8', ' Accent', ' Adam',
       ' Agila', ' Amarok', ' Amica', ' Ampera', ' Antara', ' Arteon',
       ' Astra', ' A...
       'E Class'], dtype=object),
                                                                            array(['Automatic', 'Manual', 'Other', 'Semi-Auto'], dtype=object),
                                                                            array(['Diesel', 'Electric', 'Hybrid', 'Other', 'Petrol'], dtype=object),
                                                                            array(['Audi', 'BMW', 'ford', 'hyundi', 'merc', 'skoda', 'toyota',
       'vauxhall', 'volkswagen'], dtype=object)]),
                                                  ['model', 'transmission',
                                                   'fuelType',
                                                   'Manufacturer'])])),
                ('linearregression', LinearRegression())])

In [23]:
y_pred=pipe.predict(x_test)

In [24]:
y_pred

array([15322.56878734, 13000.82696764, 26156.51357973, ...,
       -2373.74069707, 11872.01523469, 10430.91241118])

In [25]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97712 entries, 0 to 97711
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         97712 non-null  object 
 1   year          97712 non-null  int64  
 2   price         97712 non-null  int64  
 3   transmission  97712 non-null  object 
 4   mileage       97712 non-null  int64  
 5   fuelType      97712 non-null  object 
 6   tax           97712 non-null  int64  
 7   mpg           97712 non-null  float64
 8   engineSize    97712 non-null  float64
 9   Manufacturer  97712 non-null  object 
dtypes: float64(2), int64(4), object(4)
memory usage: 7.5+ MB


In [26]:
r2_score(y_test,y_pred)

0.7963924576247464

In [27]:
scores=[]
for i in range(100):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    scores.append(r2_score(y_test,y_pred))
    print(i,r2_score(y_test,y_pred))

0 0.7852996827974104
1 0.7931685310850267
2 0.8056888752135356
3 0.804116236692187
4 0.7932135875263517
5 0.7979698404138662
6 0.7900347020618068
7 0.8054898110897144
8 0.8011311432921171
9 0.788361385501092
10 0.8007493643037524
11 0.7864797102914827
12 0.7823747987677835
13 0.7800999895930496
14 0.8088033048782126
15 0.7993829521842843
16 0.7880979622159233
17 0.7995255034467864
18 0.8065847010860123
19 0.8021313387794111
20 0.806359733635633
21 0.8034730506731711
22 0.7880621635019174
23 0.8015576582274472
24 0.8012271780534023
25 0.7675700032356284
26 0.7992639254007496
27 0.7999450844608851
28 0.7993941716697529
29 0.7957233569539549
30 0.7939314803068783
31 0.7919298348906322
32 0.7785078239315735
33 0.7781984037612611
34 0.7961222108400687
35 0.8062285464103183
36 0.7998431299912055
37 0.7977023407647815
38 0.7958292805069376
39 0.782162753009286
40 0.7797245165677426
41 0.7887837567001896
42 0.7950266461703719
43 0.7934685380408795
44 0.7954319136864806
45 0.8017090812144647
46

In [28]:
print(np.argmax(scores))

54


In [29]:
print(scores[np.argmax(scores)])

0.8102018364650838


In [30]:
x_train_1,x_test_1,y_train_1,y_test_1=train_test_split(x,y,test_size=0.2,random_state=np.argmax(scores))
lr=LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(x_train_1,y_train_1)
y_pred_1=pipe.predict(x_test_1)
r2_score(y_test_1,y_pred_1)

0.8102018364650838

In [31]:
import pickle
pickle.dump(pipe,open('LinearRegressionModelCarPricePred.pkl','wb'))

In [32]:
pipe.predict(pd.DataFrame([[' Polo','volkswagen',2019,'Petrol',55,1.6,97712,'Manual']],columns=['model','Manufacturer','year','fuelType','mpg','engineSize','mileage','transmission']))

array([10996.4799609])

In [33]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 20199903.77887567


In [34]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97712 entries, 0 to 97711
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         97712 non-null  object 
 1   year          97712 non-null  int64  
 2   price         97712 non-null  int64  
 3   transmission  97712 non-null  object 
 4   mileage       97712 non-null  int64  
 5   fuelType      97712 non-null  object 
 6   tax           97712 non-null  int64  
 7   mpg           97712 non-null  float64
 8   engineSize    97712 non-null  float64
 9   Manufacturer  97712 non-null  object 
dtypes: float64(2), int64(4), object(4)
memory usage: 7.5+ MB


In [35]:
# Recommend cars based on user's budget
def recommend_cars(user_budget):
    affordable_cars = car[car['price'] <= user_budget]
    affordable_cars = affordable_cars.sort_values(by='price',ascending=False)
    return affordable_cars.drop(['tax'],axis=1)

In [36]:
user_budget = 20000
recommended_cars = recommend_cars(user_budget)

print(recommended_cars)

          model  year  price transmission  mileage fuelType   mpg  engineSize  \
79002    Mondeo  2019  20000       Manual      110   Diesel  65.7         2.0   
24668    Passat  2019  20000    Automatic    15595   Petrol  41.5         1.5   
5232       Golf  2019  20000       Manual     1000   Diesel  57.7         1.6   
60562   E Class  2018  20000    Automatic    28000   Diesel  72.4         2.0   
14836      Kuga  2019  20000       Manual     2474   Petrol  39.2         1.5   
...         ...   ...    ...          ...      ...      ...   ...         ...   
53522     Corsa  2003    590       Manual    82000   Petrol  44.8         1.2   
71524     Focus  2003    495       Manual   177644   Petrol  41.5         1.6   
28706     Corsa  2002    495       Manual    99842   Petrol  50.4         1.0   
35922     Astra  2001    450       Manual   159000   Petrol  40.4         1.6   
14428     Agila  2003    450       Manual    90000   Petrol  43.5         1.2   

      Manufacturer  
79002 